import { NextResponse } from "next/server"
import { auth } from "@/lib/auth"
import { prisma } from "@/lib/prisma"
import { formatDate } from "@/lib/date-format"
import { jsPDF } from "jspdf"

/** Official payment receipt PDF generated by the system (finance). */
export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string; paymentId: string }> }
) {
  const session = await auth()
  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const { id: loanId, paymentId } = await params
  const payment = await prisma.payment.findFirst({
    where: { id: paymentId, loanId },
    include: {
      loan: {
        include: {
          member: { select: { name: true, memberNo: true, userId: true } },
        },
      },
      approvedBy: { select: { name: true } },
    },
  })

  if (!payment) {
    return NextResponse.json({ error: "Payment not found" }, { status: 404 })
  }
  if (payment.status !== "APPROVED") {
    return NextResponse.json(
      { error: "Receipt is only available for approved payments" },
      { status: 400 }
    )
  }

  const isFinance =
    session.user.role === "TREASURER" ||
    session.user.role === "ADMIN" ||
    session.user.role === "LOANS_CLERK" ||
    session.user.role === "DISBURSING_STAFF" ||
    session.user.role === "CASHIER"
  const isMember = payment.loan.member.userId === session.user.id
  if (!isFinance && !isMember) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const doc = new jsPDF()
  const pageW = doc.internal.pageSize.getWidth()
  const margin = 24
  const contentW = pageW - margin * 2
  let y = 0

  // Header
  doc.setFillColor(41, 57, 87)
  doc.rect(0, 0, pageW, 36, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  doc.text("MCFMP Cooperative", margin, 14)
  doc.setFontSize(16)
  doc.setFont("helvetica", "bold")
  doc.text("PAYMENT RECEIPT", pageW / 2, 26, { align: "center" })
  y = 44

  const lineHeight = 8
  const labelIndent = margin + 10
  const valueX = margin + 65

  function row(label: string, value: string) {
    doc.setFont("helvetica", "normal")
    doc.setFontSize(9)
    doc.setTextColor(100, 116, 139)
    doc.text(label, labelIndent, y + 5)
    doc.setTextColor(30, 41, 59)
    doc.setFont("helvetica", "bold")
    doc.text(value, valueX, y + 5)
    y += lineHeight
  }

  y += 6
  row("Loan No", payment.loan.loanNo)
  row("Member", `${payment.loan.member.name} (${payment.loan.member.memberNo})`)
  row("Payment date", formatDate(payment.paymentDate))
  row("Amount", payment.amount.toLocaleString("en-PH", { minimumFractionDigits: 2 }))
  row("Principal", payment.principal.toLocaleString("en-PH", { minimumFractionDigits: 2 }))
  row("Interest", payment.interest.toLocaleString("en-PH", { minimumFractionDigits: 2 }))
  row("Penalty", payment.penalty.toLocaleString("en-PH", { minimumFractionDigits: 2 }))
  row("Payment method", payment.paymentMethod ?? "—")
  if (payment.referenceNo) row("Reference no", payment.referenceNo)
  if (payment.approvedBy?.name) row("Approved by", payment.approvedBy.name)
  y += 14

  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  doc.setTextColor(148, 163, 184)
  doc.text(
    "This is an official payment receipt issued by MCFMP Cooperative.",
    pageW / 2,
    y,
    { align: "center" }
  )
  doc.text("MCFMP Cooperative — Money Lending & Management System", pageW / 2, y + 5, { align: "center" })

  const buf = Buffer.from(doc.output("arraybuffer"))
  const dateStr = formatDate(payment.paymentDate).replace(/-/g, "")
  const filename = `Payment_Receipt_${payment.loan.loanNo}_${dateStr}.pdf`
  return new NextResponse(buf, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="${filename}"`,
    },
  })
}
