"use client"

import { FileText } from "lucide-react"
import { Button } from "@/components/ui/button"

type ViewPaymentReceiptButtonProps = {
  loanId: string
  paymentId: string
  /** Optional: show as compact icon-only button */
  variant?: "default" | "link"
  size?: "sm" | "icon-sm"
}

/** Opens the official payment receipt PDF (generated by finance), not the member's uploaded reference. */
export function ViewPaymentReceiptButton({
  loanId,
  paymentId,
  variant = "default",
  size = "sm",
}: ViewPaymentReceiptButtonProps) {
  const receiptUrl = `/api/loans/${loanId}/payments/${paymentId}/receipt/pdf`

  return (
    <Button
      type="button"
      variant={variant === "link" ? "link" : "outline"}
      size={size}
      className={variant === "link" ? "h-auto p-0 text-xs" : ""}
      onClick={() => window.open(receiptUrl, "_blank", "noopener,noreferrer")}
      title="View official receipt (PDF)"
    >
      <FileText className="size-3.5" />
      {size !== "icon-sm" && " View receipt"}
    </Button>
  )
}
